### ISSUE TITLE
E-mail from Google Forms not received

### ISSUE THREAD

**Issue by dyve** [niftylettuce/forward-email#100]
When using a Google Form, I do not receive the results on my forward-email-ed address (forwarded to Gmail). When I use my Gmail address, I receive the mail instantly.

There is no email in my spam filter or elsewhere.

The sender address from Google Forms is forms-receipts-noreply@google.com.

No further investigation possible for me.

**Comment by niftylettuce** [comment]
This is now resolved.  Emails will send through our system properly if they have SPF of none, neutral, or pass result or if the email itself does not even have a DKIM signature.  This is much more lax while still enforcing both email standards.  Hope this helps.  The fixes are deployed and you can test immediately.  Let me know of any issues. thank you.

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.
