### ISSUE TITLE
Not receiving some emails

### ISSUE THREAD

**Issue by whatisthisidont** [niftylettuce/forward-email#103]
Hi.
I've noticed that there are some emails that are simply not being forwarded to me.
This has happened quite a few times, but the latest is the verification email for my Adobe Creative Cloud account.
Title is "Behance & Adobe ID: Please verify your email address", sender is "account-noreply@adobe.com".
My email I could give you privately.
Would appreciate an answer very much.
Thanks so much for your project!

**Comment by niftylettuce** [comment]
This is now resolved.  Emails will send through our system properly if they have SPF of none, neutral, or pass result or if the email itself does not even have a DKIM signature.  This is much more lax while still enforcing both email standards.  Hope this helps.  The fixes are deployed and you can test immediately.  Let me know of any issues. thank you.

**Comment by niftylettuce** [comment]
This is now resolved.  Emails will send through our system properly if they have SPF of none, neutral, or pass result or if the email itself does not even have a DKIM signature.  This is much more lax while still enforcing both email standards.  Hope this helps.  The fixes are deployed and you can test immediately.  Let me know of any issues. thank you.

**Comment by JCAguilera** [comment]
I'm having the same issues, I'm unable to get confirmation emails

**Comment by ivanslater** [comment]
Im not receiving some e-mails... mostly sent from gmail.. 

421 SPF validation failed with result "permerror" and explanation "SPF Permanent Error: Too many DNS lookups"

**Comment by niftylettuce** [comment]
@JCAguilera @ivanslater 	can you please try again?

Also @ivanslater I'm guessing we're getting rate limited by Gmail.  I will go ahead and implement DNS caching with expire time of 60 seconds or something, need to research this more to see what our limit actually is.

**Comment by niftylettuce** [comment]
@ivanslater according to the RFC, the max lookups is 10.  We abide strictly by RFC 4408 and RFC 7208 protocol.  If you provide me with your domain name or forward me an email you're trying to receive I can help you further, perhaps we can solve this together.  Email me at niftylettuce@gmail.com

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.
