### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by PabloSzx** [niftylettuce/forward-email#105]
Hello, how can i know if i have an error or if the dns is still not propagated, right now i'm waiting like 2 days hoping for the propagation to work, but every time i get the same error: "550 Invalid forward-email TXT record".

Right now i have about 12 successful email forwarding done, but i'm having trouble with the another two, where i'm having the same error every time i try.
Is there any way i can check if your server got the TXT record right and i'm not the one with the problem?

**Comment by niftylettuce** [comment]
@PabloSzx 	feel free to email me at niftylettuce@gmail.com with your domain name you're using and I can investigate further with you 👍

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.

**Comment by PabloSzx** [comment]
Thanks, my issue was the last weekend, since yesterday everything is working very fast 😃
