### ISSUE TITLE
Delivery error - Malformed answer from server

### ISSUE THREAD

**Issue by bdeeming** [niftylettuce/forward-email#106]
Hello,
I recently started getting delivery failures when sending email from one forward mail address to another. The email was sent from Gmail, using Zoho Mail as an SMTP server. The receiving email is also a (different) Gmail address. Below is a copy of the response that Zoho Mail gave me when sending the email.

It doesn't appear to be a problem generally. E.g. I can send email from my gmail to my work email, and from work to my ForwardMail email just fine. Sending email to myself (via the Forward Mail address) works fine.

The only other detail I can offer, is that I have failed to receive an email from my dentist, and also https://www.recalls.govt.nz/subscriptions (attempting to sign up). Not sure if they failed for the same reason or not (they didn't show up in my Gmail spam folder at least).

Thanks in advance for any help you can provide!

(I've slightly sanitized the addresses below).

```
Delivered-To: bxx@deeming.nz
Received: from mail.zoho.com by mx.zohomail.com
    with SMTP id 1551919476671892.9603008344286; Wed, 6 Mar 2019 16:44:36 -0800 (PST)
Date: Wed, 06 Mar 2019 16:44:36 -0800
From: mailer-daemon@mail.zoho.com
To: bxx@deeming.nz
Message-Id: <169559befbe.d10e9b79782356828.-8852004435267313109@zohomail.com>
In-Reply-To: <CAOnD=VL+LTGi0oMC0RPeFwW9=hHcFegtdcf_4FpTXspOtngF1Q@mail.gmail.com>
References: <CAOnD=VL+LTGi0oMC0RPeFwW9=hHcFegtdcf_4FpTXspOtngF1Q@mail.gmail.com>
Subject: Mail Delivery Status Notification (Delay)
MIME-Version: 1.0
Content-Type: multipart/mixed;
    boundary="----=_Part_57403_1024301331.1551919476670"
User-Agent: Zoho Mail
X-Mailer: Zoho Mail
X-ZohoMail-Owner: <169559befbe.d10e9b79782356828.-8852004435267313109@zohomail.com>+zmo_0_null


------=_Part_57403_1024301331.1551919476670
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 7bit

This message was created automatically by mail delivery system.

THIS IS A WARNING MESSAGE ONLY.

YOU DO NOT NEED TO RESEND YOUR MESSAGE.

The original message was received at Wed, 06 Mar 2019 16:44:36 -0800
from bxx@deeming.nz [bxx@deeming.nz]

----- The following addresses had fatal errors -----
**[Status: Error, Address: <fxxx@deeming.nz>, Malformed answer from server]**

Message will be retried for 4 more day(s)

----- Transcript of session follows -----

Received:from mail-ed1-f43.google.com (mail-ed1-f43.google.com [209.85.208.43]) by mx.zohomail.com
    with SMTPS id 1551916762116808.9217301947657; Wed, 6 Mar 2019 15:59:22 -0800 (PST)
Message-ID:<CAOnD=VL+LTGi0oMC0RPeFwW9=hHcFegtdcf_4FpTXspOtngF1Q@mail.gmail.com>
Date:Thu, 7 Mar 2019 12:59:08 +1300
From:B Deeming <bxx@deeming.nz>
To:F Deeming <fxxx@deeming.nz>
Subject:Re: Booking confirmation: Cassia
Content-Type:multipart/alternative; boundary="000000000000314829058375c7c2"
------=_Part_57403_1024301331.1551919476670--
```

**Comment by bdeeming** [comment]
Just did another test with an empty email (subject only) and that got through just fine. 
The messages that were failing were forwards of existing emails, so I tried forwarding a random email and that worked also. 
So then I tried forwarding one of the exact emails that failed previously, and that appears to have reproduced the failure (still waiting for the failure message to come through, prob 45mins, however it hasn't arrived at the destination in over 10mins so far, so fairly confident).
I can provide you with the full email directly if needed.

**Comment by niftylettuce** [comment]
Can you send it to niftylettuce@gmail.com?

**Comment by bdeeming** [comment]
Confirmed, I got the failure message. I've forwarded the email to you untouched.

Thanks heaps!

**Comment by niftylettuce** [comment]
@bdeeming 	can you please try again?  I just deployed a fix for recent SPF/DKIM issues that I overlooked unfortunately when I was attempting to make the service more lenient whilst being spam-free

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.
