### ISSUE TITLE
my confirm email was block by mx1.forwardemail.net

### ISSUE THREAD

**Issue by ruandao** [niftylettuce/forward-email#107]
host mx1.forwardemail.net[178.128.149.101] said: 554 Message detected as spam (spam score was 7.6) (in reply to end of DATA command)
--

[mail.txt](https://github.com/niftylettuce/forward-email/files/2949276/mail.txt)

**Comment by ruandao** [comment]
i just write some test message

**Comment by niftylettuce** [comment]
Can you send me what your test message was @ruandao 	?

**Comment by niftylettuce** [comment]
Or try again?  I just deployed a fix that may have resolved your issue

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.
