### ISSUE TITLE
Sudden issue with some emails not being received #550 DKIM error

### ISSUE THREAD

**Issue by jayporter** [niftylettuce/forward-email#108]
Hi there,

Thank you for this great product.

Recently, I suddenly noticed that several subscription lists I'm on stopped making it through my email forwarder, and weren't in any of my spam folders.  However, other subscriptions continue to arrive just fine.  This started sometime on or after March 7.

Then I similarly couldn't receive my login confirmation information email from Zeit.co (importantly, this is needed to lookup/change my DNS settings!).  However, other emails arrived just fine.

Then a family member told me their email bounced, and they sent me a copy of the response to a different email address.  The response said "The response from the remote server was:550 The email you sent has an invalid DKIM signature, please try again or check your email service's DKIM configuration. If you believe this is an error, please forward this email to: support@forwardemail.net".

Let me know if you would like me to send the complete information in that error message with headers, etc.

This looks to be similar to other recent posts here, so maybe it's all connected?  Or did I inadvertently change something and break my configuration?  I was able to get a look at the DNS settings for my domain and they appear correct (I can send you that information as well in a screen shot).

Thanks again, I hope this is helpful.

Best 
Jay Porter

**Comment by niftylettuce** [comment]
@jayporter  	can you please try again?  I just deployed a fix for recent SPF/DKIM issues that I overlooked unfortunately when I was attempting to make the service more lenient whilst being spam-free

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.

**Comment by jayporter** [comment]
Thanks for your attention and kind reply -
Jay
