### ISSUE TITLE
Can't send email using Gmail

### ISSUE THREAD

**Issue by unomind** [niftylettuce/forward-email#113]
Hi, thank you for your great work.
I try to send email using myname@mydomain.tld to someone@gmail.com. But always rejected.
someone@gmail.com just an example of valid gmail account.
I have done setup email alias at my gmail account.

The error say:
Final-Recipient: rfc822; sumarsono.visione@gmail.com
Action: failed
Status: 5.0.0
Diagnostic-Code: smtp; Unauthenticated email from sumarsono.com is not accepted due to domain's DMARC policy. Please contact the administrator of sumarsono.com domain if this was a legitimate mail. Please visit https://support.google.com/mail/answer/2451690 to learn about the DMARC initiative. g7sor2225988ywa.193 - gsmtp
Last-Attempt-Date: Mon, 18 Mar 2019 18:58:28 -0700 (PDT)

Any idea?

**Comment by niftylettuce** [comment]
The DMARC policy for sumarsono.com is:

```sh
v=DMARC1; p=reject; rua=mailto:postmaster@sumarsono.com; ruf=mailto:postmaster@sumarsono.com; sp=none; ri=86400
```

Which states to reject all emails that don't have SPF nor DKIM.

The email you are sending from doesn't have SPF nor DKIM apparently set up.
