### ISSUE TITLE
Mail to forwardemail.net was bounced -- any document about error code explanation?

### ISSUE THREAD

**Issue by fweng322** [niftylettuce/forward-email#115]
Mail sent to me via forwardemail.net was bounced with server reply

554 5.4.0 <ms1.forwardemail.net #4.4.1>

nothing else.  I couldn't find any document describing this error code.  Do you have any document explaining these error codes?

**Comment by niftylettuce** [comment]
I think you have a typo with your MX server set in your DNS config, it's mx1* not ms1*.

**Comment by fweng322** [comment]
Sorry, the DNS setting is correct.  The typo was at when I typed it from the sxreenshot sent by my customer.

**Comment by niftylettuce** [comment]
@fweng322 Still an issue?

**Comment by fweng322** [comment]
Yeah, because my question is that I cannot find any document describing the error code.  Some of my client's mails were blocked by forwardemail.net and I need to explain the reason to them.
