### ISSUE TITLE
Forward-email on Zeit.co

### ISSUE THREAD

**Issue by cpup22** [niftylettuce/forward-email#116]
I'd love to use forward-email for my zeit.co deployments. I'm able to follow all of the steps except setting the SPF record

`

Name/Host/Alias | TTL | Record Type | Value/Answer/Destination
-- | -- | -- | --
@ or leave blank | 3600 | SPF | v=spf1 a mx include:spf.forwardemail.net -all

`

They don't support SPF DNS records at this time. https://zeit.co/docs/v2/domains-and-aliases/dns/ 

When I test the emails I receive an error
`550 Invalid forward-email TXT record`

Could this be related to the SPF entry? Anything else to look into to figure out why the forwarding isn't working? 

My mx records:
`MX       10 mx1.forwardemail.net.           
  MX       20 mx2.forwardemail.net.    `

**Comment by niftylettuce** [comment]
What's your domain name?  Have you used `dig` to check that your DNS
records set have propagated already?  Sometimes it takes 24 hours.

**Comment by cpup22** [comment]
lisaseacat.com 

I tried MXToolbox and it shows the correct mx records: https://mxtoolbox.com/SuperTool.aspx?action=mx%3alisaseacat.com&run=toolpage

**Comment by JeffHiggy** [comment]
Looking at your TXT record it looks like you missed the @ in the email address
forward-email=cpup22gmail.com
should be
forward-email=cpup22@gmail.com
https://mxtoolbox.com/SuperTool.aspx?action=txt%3alisaseacat.com

As for the SPF records, they are just TXT records so they are set the same as the forward-email record

**Comment by cpup22** [comment]
@JeffHiggy thank you. Sure enough, forgot the @ sign. I modified and am still seeing the error about the forward-email being TXT record being invalid. mxtoolbox and dig show the changes. But I'll give it a second and try again...

**Comment by cpup22** [comment]
Working now. Thank you @JeffHiggy @niftylettuce ! Awesome service.
