### ISSUE TITLE
Server did not respond to our request

### ISSUE THREAD

**Issue by kaashifhamid** [niftylettuce/forward-email#117]
Hi there,
I am struck when configuring this "Send emails through your SMTP server". Here's the complete error message.
_Authentication failed. Please check your username/password.
Server returned an error: "The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720 [mx1.forwardemail.net 178.128.149.101: unable to read banner], code: 0"_

Appreciate your help on this.
Thanks!

**Comment by niftylettuce** [comment]
Still an issue?
