### ISSUE TITLE
reply-to address not getting filled

### ISSUE THREAD

**Issue by sebleedelisle** [niftylettuce/forward-email#118]
Hi there, thanks so much for this service! 

I thought you might like to know that I've been getting emails from no-reply@forwardemail.net without the reply-to field filled in. It's only happening on one particular sender. Is there anything I can do to help you track this down? 

cheers!

Seb

**Comment by thomasfedb** [comment]
Would it be possible to use SRS rewriting for the `From` field rather than the no-reply address?

**Comment by nickhod** [comment]
Me too, see https://github.com/niftylettuce/forward-email/issues/101#issuecomment-481617337

Also let me know if there's anything I can do to test.

**Comment by niftylettuce** [comment]
What is the sender and FROM address that you're getting the Reply-To stripped from?

I believe Gmail strips Reply-To on any email from Facebook out of the box.

**Comment by nickhod** [comment]
Thanks for the info. The sender and from address are shown as
Facebook <no-reply@forwardemail.net>

**Comment by karelv** [comment]
Sorry, I made possibly a duplicate #124.

**Comment by niftylettuce** [comment]
This has been fixed in my latest commit and the patch is deployed to production.  Thanks for reporting the issue!! :tada:
