### ISSUE TITLE
Blacklisted by SORBS DUHL ?

### ISSUE THREAD

**Issue by plhnk** [niftylettuce/forward-email#119]
I've been trying to set the forward-email up, followed all the instructions (great documentation btw! thanks 😄) — but email still isn't coming through, so I tested using ismyemailworking.com, here's the log:
```
03/26/2019 03:01:24 - [Selected target email server to test 'First Available']
03/26/2019 03:01:26 - [Starting SMTP Session]
03/26/2019 03:01:26 - [Attempting to connect to 'mx1.forwardemail.net/178.128.149.101']
03/26/2019 03:01:26 - [Connecting to 178.128.149.101:25.]
03/26/2019 03:01:26 - [Connected, localEP='108.60.212.145:57123'; remoteEP='178.128.149.101:25'.]
03/26/2019 03:01:26 - 550 [108.60.212.145] is not a FQDN
03/26/2019 03:01:26 - [Failed to connect to 'mx1.forwardemail.net/178.128.149.101']
03/26/2019 03:01:26 - [Attempting to connect to 'mx2.forwardemail.net/178.128.149.101']
03/26/2019 03:01:26 - [Failed to connect to 'mx2.forwardemail.net/178.128.149.101']
03/26/2019 03:01:30 - [Attempting to transmit 'helo/ehlo']
03/26/2019 03:01:30 - EHLO IsMyEmailWorking.com
03/26/2019 03:01:30 - 
03/26/2019 03:01:30 - [Exception: Value cannot be null. Parameter name: line]
03/26/2019 03:01:30 - ['helo/ehlo' transmission failed]
03/26/2019 03:01:30 - [Attempting to disconnect]
03/26/2019 03:01:30 - QUIT
03/26/2019 03:01:30 - [Remote host closed connection.]
03/26/2019 03:01:30 - [Disconnected.]
03/26/2019 03:01:30 - [Disconnect success, SMTP Session terminated]
```

Using mxtoolbox.com's domain health report, I got a "Blacklisted by SORBS DUHL" for both 
 `mx1.forwardemail.net` and `mx2.forwardemail.net`:

<img width="1127" alt="Screen Shot 2019-03-26 at 8 03 51 AM" src="https://user-images.githubusercontent.com/10226086/55008079-b7958500-4f9d-11e9-87dd-ae3c6bb1a9ec.png">

Did I miss a record, or is this an actual problem?

Thanks!

**Comment by niftylettuce** [comment]
The error message is clear "550 [108.60.212.145] is not a FQDN".

The website ismyemailworking.com is not properly testing email sending, they are testing using a random IP not associated to a domain name.  The error response code from our server is `550` and it states that the IP is not a fully qualified domain name.

DNS takes sometimes 24 hours to propagate, so if you still aren't receiving test emails within 24 hours let me know.

**Comment by plhnk** [comment]
Thanks for the explanation @niftylettuce — sorry I didn't quite understand the error message!

I'm still not getting test emails — checking mxtoolbox for my domain still shows the SORBS DUHL blacklist...any help would be appreciated.

**Comment by niftylettuce** [comment]
The SORBS DUHL blacklist is irrelevant.  How are you sending test emails?  If you send me an email privately at niftylettuce@gmail.com I'd be glad to send you a few test emails.  I'm not sure what domain you're using.
