### ISSUE TITLE
Allow domain alias forwarding

### ISSUE THREAD

**Issue by wei** [niftylettuce/forward-email#12]
Thank you for this awesome project!

If I have primarydomain a.com that already has email service setup. Can we include the ability so all mails to {username}@b.com can be forwarded to corresponding {username}@a.com?

Looks like we just need to modify this part
https://github.com/niftylettuce/forward-email/blob/cbf58fcbb01ac7539b08b95a5720606a4889a3bd/index.js#L548-L553
to handle TXT records like
`forward-email=b.com` or `forward-email=@b.com`

What do you think?

**Comment by matteotrubini** [comment]
It's a useful cPanel feature that simplifies domain alias configuration, as you doesn't need to create and keep updated the email account list.

**Comment by matteotrubini** [comment]
@niftylettuce it seems to me that this issue is not covered - or there's a miss in doc?

**Comment by niftylettuce** [comment]
I had to roll back to a previous commit due to a loophole - I've already fixed it, just need to get back to my desk and deploy.  Will ping you here once it's back up and also link you to the commit showing fixes.

**Comment by niftylettuce** [comment]
This has been back up and working for a while now btw, I forgot to update this comment and let you know.

**Comment by matteotrubini** [comment]
Which is the syntax to forward any {username}@example.com to corresponding {username}@example.net automagically?
It seems to me that the issue is not covered.

**Comment by niftylettuce** [comment]
`foo:test@example.net` will forward `foo@example.com` to `test@example.net`

**Comment by niftylettuce** [comment]
See the README @matteotrubini

**Comment by matteotrubini** [comment]
> Can we include the ability so all mails to {username}@b.com can be forwarded to corresponding {username}@a.com?

> to handle TXT records like
> `forward-email=b.com` or `forward-email=@b.com`

No username required, only domains.

Ref: https://documentation.cpanel.net/display/80Docs/Forwarders#Forwarders-Domainforwarders

**Comment by niftylettuce** [comment]
Ah ok give me a few

**Comment by niftylettuce** [comment]
:tada: Released in v2.1.3 and deployed to production.  It's good to go.

Try it out!  Also note the README has an updated example for domain alias forwarding:

<img width="912" alt="Screen Shot 2019-06-28 at 12 37 44 PM" src="https://user-images.githubusercontent.com/523141/60360545-8fa12d80-99a1-11e9-82f6-2876cb955f8f.png">

Ref:
- https://github.com/niftylettuce/forward-email/releases/tag/v2.1.3
- https://github.com/niftylettuce/forward-email/commit/8c20e2acc177c06b8839e72091d38e5eb1ef8b78

**Comment by matteotrubini** [comment]
you make my day guy :smile:
