### ISSUE TITLE
Forwarding to GMX/Web is rejected

### ISSUE THREAD

**Issue by MiXT4PE** [niftylettuce/forward-email#121]
I get this when sending an email:

```
The following addresses had fatal errors -----

  [Status: Error, Address: <redacted@domain.com>, Malformed answer from server]

Message will be retried for 4 more day(s)

   ----- Transcript of session follows -----

Received:from [10.208.250.157] (x2f7f69d.dyn.telefonica.de [2.247.246.157]) by mx.zoho.eu

with SMTPS id 1554270712214799.5572657283942; Wed, 3 Apr 2019 07:51:52 +0200 (CEST)

Message-ID:<169e1bd04d8.2789.a8c80f308366c37fb6835606d612636a@redacted>

Date:Wed, 03 Apr 2019 07:51:44 +0200

From:Redacted <redactedemail>

User-Agent:AquaMail/1.19.0-1434 (build: 101900002)

To:<redacted@domain.com>

Subject:Test

Content-Type:text/plain; format=flowed; charset="us-ascii"
```

I found this in the [Email policy of GMX](https://postmaster.gmx.com/en/email-policy#PTR):

>The delivering email server must have a static IP address. Additionally, it has to be configured correctly and needs to provide a valid HELO, as well as MX, A, and PTR resource records (reverse DNS entry). The PTR-RR in particular must not correspond to the preset generic record of the host.

I am using the online free version and am Not self-hosted. When I point it to another email-address it works just fine.

**Comment by niftylettuce** [comment]
Where are you sending FROM and TO?  Feel free to share privately in an email to niftylettuce@gmail.com.

**Comment by MiXT4PE** [comment]
I sent you an email and contacted you on Twitter but you never replied :/
