### ISSUE TITLE
protonmail.com and domain created with godaddy

### ISSUE THREAD

**Issue by karelv** [niftylettuce/forward-email#124]
The email which I send with a protonmail account is indeed forwarded, I can read the message in my own mailbox. Great! 
I even can see the name of who send it to me, however I cannot see the email-address of the sender.
![image](https://user-images.githubusercontent.com/787006/55912936-bb531980-5be3-11e9-82cd-74d911d1686f.png)

Is there anything I can do to correct it (a configuration on my godaddy DNS settings of my website), or is it related to something with forwardemail.net?

Thanks,
Karel.

**Comment by niftylettuce** [comment]
This has been fixed in my latest commit and the patch is deployed to production.  Thanks for reporting the issue!! :tada:

**Comment by karelv** [comment]
Confirmed!

Thanks a lot
