### ISSUE TITLE
html message are not working well

### ISSUE THREAD

**Issue by j2l** [niftylettuce/forward-email#125]
@niftylettuce, thank you again, I'm delighted with your free service. It revives my domain name.

I just have an issue with messages in html from Patreon, I receive them with a strange format:
```
=0D
--
=0D   Grow =0D your fanbase and grow your income with in-depth guides, case studies, and = =0D resources.=0D | =0D
=0D
...
```
It's not super critical since html is from marketing sources but I wonder if I can do something to fix it.

**Comment by niftylettuce** [comment]
should be resolved now!

version 2 is released!
