### ISSUE TITLE
My own email is added automatically as carbon copy

### ISSUE THREAD

**Issue by Guisardo** [niftylettuce/forward-email#126]
Hi there,
Thanks for this great project!
When someone sends me an email, the forwardemail.net automatically adds my mail address as CC to the original mail. This provokes that every time I make a reply from a mail client, my own mail address is added again to the CC.
The headers of the first mail looks something like this after going through forwardemail.net:
```
From: Sender User Name <no-reply@forwardemail.net>
To: "'Guisardo'" <guisardo@example.com.ar>
Cc: guisardo@example.com.ar
Reply-To: Sender User Name <sender@otherexample.com.ar>
```
If my email address is already at the TO it should NOT be added also as CC by the system.
Best,

**Comment by niftylettuce** [comment]
Nowhere does our system set the CC.  This must be something on your side.  Please send an original email with raw headers and content to support@forwardemail.net if you need more help.

**Comment by niftylettuce** [comment]
Nowhere does our system set the CC.  This must be something on your side.
Please send an original email with raw headers and content to
support@forwardemail.net if you need more help.
