### ISSUE TITLE
Make a npm release

### ISSUE THREAD

**Issue by synox** [niftylettuce/forward-email#127]
https://www.npmjs.com/package/forward-email is empty. 

also the installed package:

    $ npm install forward-email
    $ find node_modules/
    node_modules/
    node_modules//forward-email
    node_modules//forward-email/package.json

I find https://github.com/sindresorhus/np very easy to use.

**Comment by niftylettuce** [comment]
It's on the agenda in the future, I already use `np`

**Comment by niftylettuce** [comment]
v2.0.0 is released and v2.0.1 is releasing soon today
