### ISSUE TITLE
Make redis optional

### ISSUE THREAD

**Issue by synox** [niftylettuce/forward-email#128]
It should be possible to use it without a redis server, and fall back to a in-memory rate limiter. This makes runtime setups simpler for some people.

**Comment by niftylettuce** [comment]
PR welcome

**Comment by joksnet** [comment]
Maybe start by mocking redis in the tests or using something like [fakeredis](https://www.npmjs.com/package/fakeredis).

**Comment by niftylettuce** [comment]
I'm adding support in the next release so you can pass `limiter: false` as an option.
