### ISSUE TITLE
v3 Thoughts

### ISSUE THREAD

**Issue by niftylettuce** [niftylettuce/forward-email#131]
I think perhaps we could bind an `.on('headers')` event for the `messageSplitter` and start performing DNS lookups well in advance of the message being completely piped across the stream and read.

**Comment by niftylettuce** [comment]
We should also cache DNS lookups with Redis, and it'd be great if we could get our python scripts to re-use that cached DNS result as well in the future.

**Comment by dagelf** [comment]
Or 9.9.9.9, or the one provided by your host

**Comment by niftylettuce** [comment]
We will be implementing a local resolver when I set up global load balancing on this service.
