### ISSUE TITLE
Invalid DKIM signature

### ISSUE THREAD

**Issue by onaralili** [niftylettuce/forward-email#132]
I generated a public-private key pair and configured DKIM record (TXT) using the public key. Also validated on https://dkimcore.org/tools/ and looks like DKIM record properly configured.

However, I am still getting `550 The email you sent has an invalid DKIM signature` when I send a test email from outlook.com. 

It seems to be working from other email providers (tested with protonmail.)

The domain is: oopspam.com

**Comment by niftylettuce** [comment]
@onaralili can you FWD me the complete raw email?  You may need to purge the cache using Cloudflare's purge cache tool at https://1.1.1.1/purge-cache/.  Not sure where you're sending FROM and TO - would be helpful to know.  Feel free to send email to support@forwardemail.net.

**Comment by onaralili** [comment]
> @onaralili can you FWD me the complete raw email? You may need to purge the cache using Cloudflare's purge cache tool at https://1.1.1.1/purge-cache/. Not sure where you're sending FROM and TO - would be helpful to know. Feel free to send email to [support@forwardemail.net](mailto:support@forwardemail.net).

I tried to forward you the email and got the same rejection email. I'm going to forward from my gmail address.

**Comment by niftylettuce** [comment]
This is an issue with the configuration on Outlook and your own DKIM setup.  Our service is confirming that your DKIM record signature is invalid.

**Comment by onaralili** [comment]
> This is an issue with the configuration on Outlook and your own DKIM setup. Our service is confirming that your DKIM record signature is invalid.

Thanks, going to try to configure DKIM differently and test again.

**Comment by onaralili** [comment]
@niftylettuce I am pretty sure my DKIM signature is valid. If I understand correctly, there is a problem on Outlook's end?
