### ISSUE TITLE
How to Setup DKIM

### ISSUE THREAD

**Issue by tynlc** [niftylettuce/forward-email#136]
Hi,

This is my first time to post and I'm just wondering to setup DKIM. From: https://dkimcore.org/.

Thanks

**Comment by Biep** [comment]
I have the same problem.  The FAQ tells me (in autotranslated Dutch:
"Ga naar [Mijn Account Domeinen](https://forwardemail.net/my-account/domains) Instellingen Uitgaande SMTP-configuratie en volg de installatie-instructies." - but if I go there, I en up on [this page](https://forwardemail.net/nl/guides/send-email-with-custom-domain-smtp), which doesn't even mention DKIM.
(Technically I didn't follow the instructions: on the domain page I first selected the relevant domain before choosing "Settings" (or whatever the original English name of the link was)..)

**Comment by titanism** [comment]
You need to go to the Advanced Settings page for your domain.  Click "Complete Setup":

<img width="1136" alt="Screen Shot 2024-02-27 at 5 25 36 PM" src="https://github.com/forwardemail/free-email-forwarding/assets/101466223/e9aa8f31-117b-406b-9f4a-f3124881f640">

**Comment by Biep** [comment]
Thanks!
I do'n see this page when I go there, so I suppose this is only in some paid plan.
I only want to use FrowardEmail for incoming mail, so I am not sure I even need to set DKIM.  It is just that Zoho keeps buggering me.


Thanks for the great service!







---- Op Wed, 28 Feb 2024 00:26:56 +0100 schreef titanism ***@***.***> ----





You need to go to the Advanced Settings page for your domain.  Click "Complete Setup":

https://github.com/forwardemail/free-email-forwarding/assets/101466223/e9aa8f31-117b-406b-9f4a-f3124881f640 —

**Comment by titanism** [comment]
@Biep  correct this is for paid plan only
