### ISSUE TITLE
550 queryTxt ESERVFAIL with Cloudflare DNS

### ISSUE THREAD

**Issue by iburistu** [niftylettuce/forward-email#140]
First of all, thank you for providing this free service!

I'm running into some issues setting up the email forwarding for a custom domain that's using Cloudflare's DNS nameservers.  I've followed along with the instructions but haven't been able to get messages to forward correctly.  Each time I've tried, I've gotten 550 errors as a response, and I've been purging the cache and waiting for the `dig` output to change before modifying anything.  

Things are further complicated with my domain provider;  not sure if Google Domains is in the same boat as Google Apps when it comes to SPF.

Here's my `dig` output:

```
$ dig linkletter.dev MX +short
10 mx1.forwardemail.net.
20 mx2.forwardemail.net. 
$ dig linkletter.dev TXT +short
"forward-email=zack:zlinkletter@yahoo.com"
"ca3-45f9ac9472eb411396cb0b9fb1a1deec" 
$ dig linkletter.dev SPF +short
"v=spf1 a mx include:spf.forwardemail.net -all"
```

Any ideas?  I've tried variations of both the Google Apps SPF string, and adding and removing quotes around the TXT string with no luck.

Thanks again!

**Comment by dagelf** [comment]
Your DNS isn't live on the public internet! Neither is there a .dev TLD.

```
coenraad@coenraad-dell:~$ dig linkletter.dev

; <<>> DiG 9.11.3-1ubuntu1.7-Ubuntu <<>> linkletter.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 49423
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;linkletter.dev.			IN	A

;; Query time: 358 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Sun Jun 09 11:27:34 SAST 2019
;; MSG SIZE  rcvd: 32

coenraad@coenraad-dell:~$ dig linkletter.dev MX +short
coenraad@coenraad-dell:~$ 

```
Use a proper, registered, live domain if you want to use public DNS. (Or a free one, eg. from [freenom.tk](freenom.tk))

**Comment by niftylettuce** [comment]
Thank you @dagelf 	👍
