### ISSUE TITLE
Email forwarding bugged out

### ISSUE THREAD

**Issue by pandichef** [niftylettuce/forward-email#142]
Someone sent me an email this morning and I got this message out of the blue... any ideas what's causing this?

Your message couldn't be delivered. Despite repeated attempts to contact the recipient's email system it didn't respond.
Contact the recipient by some other means (by phone, for example) and ask them to tell their email admin that it appears that their email system isn't accepting connection requests from your email system. Give them the error details shown below. It's likely that the recipient's email admin is the only one who can fix this problem.

For more information and tips to fix this issue see this article: https://go.microsoft.com/fwlink/?LinkId=389361.

Note: This happened just once yesterday morning.  In general, it works great.  It feels like a server was down for 2 hours and then came back up.

**Comment by niftylettuce** [comment]
Should be fine, if you have further similar issues let me know

**Comment by niftylettuce** [comment]
Also PS- we are getting a status page set up soon
