### ISSUE TITLE
One alias is supposed to forward to two different e-mail addresses (one of them being the same as the catch-all). However, only the first e-mail address gets the message.

### ISSUE THREAD

**Issue by fedus** [niftylettuce/forward-email#143]
Hello,

I have the following setup:

forward-email=ALIAS:MAIL1@DOMAIN.COM,ALIAS:MAIL2@OTHERDOMAIN.COM,MAIL2@OTHERDOMAIN.COM

So, in other words, one catch-all (MAIL2@...)
And one ALIAS which forwards mails to MAIL1@.. and MAIL2@.. (the latter is also the catch-all).

However, when mail is sent to ALIAS, it only gets delivered to MAIL1@.., and NOT MAIL2@..
The catch-all works fine though, so MAIL2@.. definitely can receive mail forwarded by forward-email.

What could be the source of this error? I don't know if there are any useful logs that I could attach?

Thanks.

**Comment by niftylettuce** [comment]
I currently have this disabled as there was a core bug (so the version deployed is a few commits rolled back).  I do however have the issues completely fixed already locally and I will be deploying/pushing an update soon.  I am adding the feature for bounces to work properly (e.g. an email gets bounced, and your address is still hidden/secure).

**Comment by niftylettuce** [comment]
This is re-enabled again per my work with commit https://github.com/niftylettuce/forward-email/commit/3f84c922a008eac2cb3c8b094b9914d90044553d

Try it out and let me know if all works well!
