### ISSUE TITLE
Cannot send email: The IP address  178.128.149.101 has been identified as not meeting PBL's  policy for IP addresses permitted to deliver  unauthenticated 'direct-to-mx' email

### ISSUE THREAD

**Issue by MagicMarvMan** [niftylettuce/forward-email#150]
Hey,

Whenever I try to send an email to my domain configured to use forwardemail.net, the email comes back with the following error:
```
The IP address 
178.128.149.101 has been identified as not meeting PBL's 
policy for IP addresses permitted to deliver 
unauthenticated 'direct-to-mx' email
```

I tried a few mail servers / providers but every provider returns this error. I have followed the whole installation guide, set up MX, TXT, SPF and DMARC records. The domain is: "diebetriebsraete.de" (I will delete this text when the issue is resolved due to privacy reasons).

Thank you,
Marvin

**Comment by niftylettuce** [comment]
This is because your IP is listed on a DNS based blackhole list.

We use this package https://github.com/silverwind/dnsbl#readme to prevent commonly used IP addresses from malicious/spam reports from sending emails.

**Comment by niftylettuce** [comment]
Let me know once you read this and I will delete issue.

**Comment by MagicMarvMan** [comment]
Hello @niftylettuce,

Many thanks for the answer! Okay, now I know what it is, but what can I do about it? Is it my mobile phone or my mail provider I'm sending from? Are all my domains somehow blacklisted? What can I do to receive/ send emails again?

**Comment by MagicMarvMan** [comment]
I have never sent spam emails to somebody and don’t know why I could be on that list with all my domains/ devices.

**Comment by MagicMarvMan** [comment]
Okay, I found the problem. I tried the forwarding with different target domains and every mail worked, except our company domain, this is hosted by the German company Strato. Do you know, why our company domain is blacklisted and how we can resolve this issue? We don’t host the email servers ourself, they are managed by strato. 

Thanks a lot.

**Comment by niftylettuce** [comment]
It may be because your Strato MX server you use for mail is blocking our IP address - in other words it thinks our IP is bad - you may need to contact them to have it whitelisted.
