### ISSUE TITLE
Self-Hosting: listen EACCES: Permission denied 0.0.0.0:25 (question)

### ISSUE THREAD

**Issue by Firewolf34** [niftylettuce/forward-email#156]
Hello!

This is probably a mis-configuration on my end, but I don't know where else to ask about this. I'm getting an error while trying to self-host the program, I've set it up as best as I can figure according to the guide and ran the NodeJS code given on the README.MD under the self-host instructions.

I changed the info in the provided index.js to fit my custom server, changing all references to forwardemail.net to my custom domain name. And I set up my DNS records using the guide, changing the references to forwardemail.net to my own domain as well.

However I seem to be getting this error upon running it with `node index.js`:
```
fatal: Not a git repository (or any of the parent directories): .git
✖  error     Error: listen EACCES: permission denied 0.0.0.0:25
    at Server.setupListenHandle [as _listen2] (net.js:1211:19)
    at listenInCluster (net.js:1276:12)
    at Server.listen (net.js:1364:7)
    at SMTPServer.listen (/home/forwardemail/node_modules/smtp-server/lib/smtp-server.js:123:28)
    at Object.<anonymous> (/home/forwardemail/index.js:27:21)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 25
} {
  app: {
    name: '',
    version: '',
    node: 'v12.8.0',
    hash: undefined,
    environment: 'development',
    hostname: 'MY_SYSTEMS_HOSTNAME',
    pid: 28153
  }
}
```

Also, one last question if I may: Do we need to specify the location of our SSL certs in this file too? I do not have a `/home/deploy` folder as far as I know. But I do have SSL certs provided by Let's Encrypt via Certbot, though I've heard those cannot be used with mail apparently.

Thanks for any help!

**Comment by ver2go** [comment]
Just a guess.  Are you root?  25 is a privileged port. Or is something
already running on 25?

**Comment by Firewolf34** [comment]
Hey, that works! Thanks!!! 

However, I was under the impression that our use of authbind allowed us to avoid using root? I'm not so sure I feel safe running an SMTP program as root! Are there any ways around this?

**Comment by niftylettuce** [comment]
Yes I have a new approach that does not use authbind and is way simpler.  In the meanwhile you should be fine using authbind.  Will release it when I release the next version of ForwardEmail...

**Comment by Firewolf34** [comment]
So does that mean I should run it under root or no? Running it not as root, results in the `EACCES: permission denied.`

Does running it as root still use authbind?

**Comment by niftylettuce** [comment]
You don't need to run under root, you need to set up authbind so it uses it.

e.g. follow steps here https://thomashunter.name/posts/2012-12-14-using-authbind-with-node-js but replace port `80` with `25`.

**Comment by Firewolf34** [comment]
Awesome!! That was the issue, I just needed to run it under authbind. I had set it all up, I just wasn't using it! D'oh! 

Thanks, and I love the program by the way. Great stuff!

Finally: Do you require us to provide our own SSL certificates to use this program?

**Comment by niftylettuce** [comment]
Yea, and you can specify key and its path too, see `index.js`.

**Comment by Firewolf34** [comment]
Great! Thanks so much for your help, guys! Gonna close this ticket now, my problems are resolved. :+1:
