### ISSUE TITLE
550 queryTxt ESERVFAIL

### ISSUE THREAD

**Issue by Helices** [niftylettuce/forward-email#159]
I'm very impressed with your service, but I'm having a weird error.
As far as I can tell everything works as promised unless the sender is using a GSuite account.
In that case the sender receives a return code "550 queryTxt ESERVFAIL"

Any help would be greatly appreciated.
Thanks!

**Comment by niftylettuce** [comment]
DNS needs to propagate, can take up to 24 hours

**Comment by Helices** [comment]
I understand DNS propagation. I requested purges on all major publicly available DNS caches and tracked the issue for 96hrs prior to reporting.

**Comment by niftylettuce** [comment]
Can your sender provide a full copy including headers of the email they are trying to send you?  What is the from address, or at least domain name?  If this is private information please email me niftylettuce@gmail.com.
