### ISSUE TITLE
No passing DKIM signature found

### ISSUE THREAD

**Issue by ramiroec** [niftylettuce/forward-email#16]
I send mail from: hotmail.com and others, and get this message.
From Gmail sends perfect.
Please help, thanks!

**Comment by TheWildHorse** [comment]
Same problem here

**Comment by niftylettuce** [comment]
Will resolve soon

**Comment by roncham** [comment]
If it helps here is the error I got back sending from Yahoo.
550: Message failed: 550-5.7.1.
Gmail works fine. Apparently YouTube emails don't since I haven't got anything yet.

**Comment by niftylettuce** [comment]
This issue should be resolved, can you please test again?  Thanks!

**Comment by roncham** [comment]
Yahoo still bounces back and now Google didn't work either.
I should note I'm using your hosted version from your site.

**Comment by niftylettuce** [comment]
If you try again it should be fine.  Let me know otherwise!  If you want to forward me any rejections/issues/bounced mail you can at niftylettuce@gmail.com for me to further investigate.  I fixed quite a few issues recently.

**Comment by niftylettuce** [comment]
Currently Yahoo does not work.  I have inquired to someone that works there to attempt to get us whitelisted - but they do not support email forwarding afaik.

**Comment by niftylettuce** [comment]
Btw if you try again with other providers than Yahoo, it should work fine.  I did make a patch to automatically accept from top 30K Alexa ranked sites (which include Outlook etc)

**Comment by onaralili** [comment]
@ramiroec hi, I have the same issue, were you able to solve the issue?
