### ISSUE TITLE
Option to Disable SSL/TLS Strict Hostname Checking

### ISSUE THREAD

**Issue by b3nda1ley** [niftylettuce/forward-email#167]
Firstly, thank you for providing this service. Is there any way of disabling strict hostname checking as I'm trying to forward to a shared mail server (with a web hosting company) where the SSL/TLS certificate host name/s don't match the domain I am forwarding to. Thanks.

**Comment by niftylettuce** [comment]
It is bad practice to not have ones that match, I would contact them to have them fix their obvious issue, thank you though.

**Comment by b3nda1ley** [comment]
Thanks for a quick response. I agree it's bad practice but they won't allow me to have my own certificate as it's a shared hosting platform. I presume most mail relays don't enforce strict checking as I never have any problem receiving mail (that I'm aware of anyway) so would appreciate it if you could consider it as an option in the future. Cheers.

**Comment by shaneparsons** [comment]
@b3nda1ley were you able to find a workaround by chance?

**Comment by b3nda1ley** [comment]
> @b3nda1ley were you able to find a workaround by chance?

Alas no @shaneparsons I had to go with a different service.
