### ISSUE TITLE
Server sent a malformed Response

### ISSUE THREAD

**Issue by mranon0007** [niftylettuce/forward-email#18]
Hello, my domain name is bytedevs.com.
I have added the TXT & MX records as mentioned in the documentation and it's been more than 24 hrs but I am still not receiving emails. When I send an email to xyz@bytedevs.com, I get a 550 error.

**Comment by niftylettuce** [comment]
I just sent a test email, let's see if you get it!

**Comment by niftylettuce** [comment]
@mranon0007 I believe that the senders that are trying to send you mail do not have DKIM or SPF.  Any sender TO your address needs to have at least one of these, or be sending from a top ranked Alexa email provider (e.g. outlook/gmail/yahoo/hotmail).  I just checked and it looks like my test email from niftylettuce@gmail.com went through!

**Comment by niftylettuce** [comment]
The reason for this is to obviously eliminate spam by ensuring best practices are used!  We need to maintain good reputation.
