### ISSUE TITLE
Spammer heaven -- need to hide the forwarding email address

### ISSUE THREAD

**Issue by mattheworiordan** [niftylettuce/forward-email#19]
I love this system, it's just awesome and hugely appreciated.  However, I think the DNS design is flawed.

Case in point:

```
$ dig forwardemail.net TXT

; <<>> DiG 9.10.6 <<>> forwardemail.net TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43407
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;forwardemail.net.		IN	TXT

;; ANSWER SECTION:
forwardemail.net.	299	IN	TXT	"forward-email=niftylettuce@gmail.com"
forwardemail.net.	299	IN	TXT	"v=spf1 a mx include:spf.forwardemail.net ~all"

;; Query time: 32 msec
;; SERVER: 10.128.128.128#53(10.128.128.128)
;; WHEN: Mon Jul 16 19:37:11 BST 2018
;; MSG SIZE  rcvd: 152
```

Should there not be a better way to hide the forwarding email address?  Spammers can now use the TXT records to find valid email addresses on a domain, which they would have otherwise struggled to find.

Ideas that may work:

* Allow a public key to be specified in the TXT record, and a private key to be uploaded to your service.
* Allow forwarding to be configured from your service (via a simple web UI) once the MX records are set up
* Provide a simple online encryption tool that will take the configuration, encrypt it using your public key, and only you will have the private key to decrypt.  This may in fact be the easiest as you can keep your system effectively stateless.

WDYT?

**Comment by wei** [comment]
Dupe of #6

**Comment by mattheworiordan** [comment]
Ok, closing in favour of #6

**Comment by niftylettuce** [comment]
This feature is now available (FOR FREE) at https://forwardein beta program (ignore the pricing, as it's free for the beta program, then after beta program is over, you will have 30 days to enter billing info).

You can easily import existing TXT records with 1-click using the "Import TXT" button in the Alias Manager.

Try it out! https://forwardemail.net/features

Feedback is welcome.

🎉

**Comment by Mistic92** [comment]
It's not available anymore in free plan
