### ISSUE TITLE
Help triaging forwarding problem

### ISSUE THREAD

**Issue by ctindel** [niftylettuce/forward-email#21]
Hi-

Any chance you could take a look at the MX and TXT records for amishscooters.com and tell me what I'm doing wrong?  I think I set everything up correctly in route53 but it doesn't seem to be working.

Thanks!
<img width="940" alt="screen shot 2018-07-25 at 12 56 12 pm" src="https://user-images.githubusercontent.com/1863749/43265663-6fd7dd3a-90b7-11e8-810c-7ba9e07d4c05.png">

**Comment by niftylettuce** [comment]
how are you testing the setup?  are you emailing yourself from
ctindel@gmail.com?

**Comment by ctindel** [comment]
@niftylettuce yes exactly

**Comment by ctindel** [comment]
Any way to make it so that emails from self come through?

**Comment by niftylettuce** [comment]
Not that I know of - you can test from another email or just check your
spam folder and mark as not spam I believe.

**Comment by ctindel** [comment]
Oddly enough I just tried for the 8th time and that one came through (the 7 i tried yesterday did not).

Gmail does give me a warning about a possibly spoofed message though.  Anyway thank you!
