### ISSUE TITLE
Multiple forwarding addresses

### ISSUE THREAD

**Issue by niftylettuce** [niftylettuce/forward-email#24]
e.g. separate with pipe `forward-email=food:niftylettuce@gmail.com|elusiveonion@gmail.com...`

**Comment by invisiblekyle** [comment]
This is exactly what I need!  Any idea when you might be able to implement it?  Thank you for your project!!!

**Comment by cactusoft** [comment]
This would be very handy. For example, on a web site you might have a generic contact address that you want to forward to two or more staff, in case one is on holiday, etc.

**Comment by invisiblekyle** [comment]
Any further thought on this?  I am able to do this via Cpanel...

**Comment by silasdavis** [comment]
I am also after this. One issue is that it obviously provides a potential target for an amplification attack so it may need to have some rate limiting applied to it.

I assume this is not already implicitly supported by defining multiple rules with the same inbound address?

**Comment by tomcontr** [comment]
I manage to modify the code to allow this. I will post it here tomorrow. It's an ugly solution because Im not an expert on this language, but it works.

Regards,

**Comment by niftylettuce** [comment]
This is re-enabled again per my work with commit https://github.com/niftylettuce/forward-email/commit/3f84c922a008eac2cb3c8b094b9914d90044553d

Try it out and let me know if all works well!
