### ISSUE TITLE
default forward address

### ISSUE THREAD

**Issue by zoqui** [niftylettuce/forward-email#25]
Please implement the ability to have a default destination mailbox

domain to be foward: **example.com**

TXT = forward-email=a:a@gmail.com,b:b@gmailcom,c@gmail.com

Please, notice the **c@gmail.com** is the default mailbox on the domain forward configuration 
So, any account that does not match to the ones listed on the TXT entry could be forward to the domain default mail address (almost like ALL EMAILS TO THE DOMAIN).

User Cases:
email to a@example.com will be forward to a@gmail.com
email to b@example.com will be forward to b@gmail.com
email to support@example.com or contact@example.com they all will be forward to c@gmail.com

**Comment by niftylettuce** [comment]
closed per #46, will be deployed shortly

**Comment by niftylettuce** [comment]
this should be fixed now btw @zoqui

**Comment by zoqui** [comment]
Thank you so much - I will be testing it and let you know
