### ISSUE TITLE
Forwarding doesn't work with Internationalized domain name (IDN)

### ISSUE THREAD

**Issue by levz0r** [niftylettuce/forward-email#26]
Hi,
First of all, thanks so much for such a solution!

I was asked to make a catch-all forwarding for a domain which is in Hebrew. After doing all what is in the guide, the forwarding still doesn't work.
Unfortunately, I can't post the domain name publicly, but would do so in a private message to whoever can investigate the issue. I can say it starts with xn----0hc

Thank you in advance.

**Comment by niftylettuce** [comment]
email me - niftylettuce@gmail.com
