### ISSUE TITLE
hotmail/outlook - Rejected because of Sender Policy Framework violation

### ISSUE THREAD

**Issue by bert-bruggeman** [niftylettuce/forward-email#29]
Hi,

I followed all steps on https://forwardemail.net/#/?id=how-it-works, everything is working fine when sending emails from gmail or other services but I can't send emails from hotmail and outlook...

- **SPF record:(TXT)**: v=spf1 a mx include:spf.forwardemail.net ~all
- hosted on netlify.com with netlify-dns

**outlook postmaster reply**:
`The message was rejected because of Sender Policy Framework violation -> 550 Please ensure the email service you are sending from either has SPF, DKIM, or is a top-ranked <30K Alexa.com domain. You can most likely resolve this problem by searching on Google for "$serviceName SPF DKIM setup" (be sure to replace $serviceName with your email service provider, e.g. "Zoho"). If you continue to have issues, please see https://forwardemail.net or file an issue on GitHub at https://github.com/niftylettuce/forward-email. We'd be glad to help out! -- @niftylettuce If you need help with email-forwarding setup or troubleshooting please visit https://forwardemail.net`

**Comment by chipironcin** [comment]
+1 it happens to me as well

**Comment by arnevanhoorn** [comment]
+1 I also have this issue

**Comment by niftylettuce** [comment]
This is probably due to a strict DMARC policy on the domain, we will most likely be re-writing the "from" to be `no-reply@forwardemail.net` and adding a `Reply-To` of your email address at Outlook for instance.

**Comment by arnevanhoorn** [comment]
Is there anything we can do about it? Users cannot send email from Hotmail/Outlook right now.

**Comment by niftylettuce** [comment]
@arnevanhoorn 	I am working on a fix as I type this

**Comment by contactalexliu** [comment]
Hi,

This seems to still be a problem with some Outlook users... Their mail is being rejected with `mx27.ess.sfj.cudaops.com #550 permanent failure for one of more recipients (<redacted> Please ensure the email service you are sending from either has SPF or DKIM. You can most...) ##`

Is the original fix not working at this point?

**Comment by niftylettuce** [comment]
This issue is already resolved.  The people that are calling you about emails being rejected need to learn and get some knowledge about email security.  They need to setup SPF or DKIM on their domains.  Otherwise it's incredibly easy to spoof emails as being "From" them.

**Comment by tombert-zz** [comment]
+1

It works from hotmail and gmail. But when trying to send an email from my companies (ATOS) outlook client I receive this: _Please ensure the email service you are sending from either has SPF or DKIM._

I cannot believe that ATOS did not setup spf right ...

thx

**Comment by niftylettuce** [comment]
@tombert-zz I replied to your other issue opened, see #80

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.
