### ISSUE TITLE
Forward all emails to multiple address

### ISSUE THREAD

**Issue by amartins** [niftylettuce/forward-email#32]
I would like to know if there is a feature to forward all emails to multiple address. 

Here is a example:

TXT "forward-email=a@gmail.com,b@gmail.com"

**Comment by jm42** [comment]
Duplicated of #24.

**Comment by niftylettuce** [comment]
thx @jm42

**Comment by niftylettuce** [comment]
This is re-enabled again per my work with commit https://github.com/niftylettuce/forward-email/commit/3f84c922a008eac2cb3c8b094b9914d90044553d

Try it out and let me know if all works well!
