### ISSUE TITLE
DNS TXT character limit of 255

### ISSUE THREAD

**Issue by mkuiphuis** [niftylettuce/forward-email#33]
I am currently using another (paid) forwarding service, but not all emails are received properly. Looking at this solution, but our txt record would have more than 255 characters, to setup 11 email forwarders.

Is there any way to split them up into multiple txt records which in turn are concatenated?

**Comment by vuolter** [comment]
Sure, you can use a service like [this](https://tools.wordtothewise.com/spf/minimize) to minify and split up your current spf record. 😉

**Comment by matteotrubini** [comment]
I would like to manage hundreds of forwarding, but with a single record will be impossible, even using quoted strings concatenation (ex: today I tried on cloudflare and it seems to support up to ~1000 chars, but it's undocumented).

@niftylettuce why record parsing is limited to first one only?

**Comment by anistark** [comment]
Same issue.
@niftylettuce Can it be resolved if I setup the project locally? and TXT records on my the project itself?

**Comment by niftylettuce** [comment]
@mkuiphuis @matteotrubini @anistark I've just released and deployed support for this, please try it out.
