### ISSUE TITLE
DKIM for GoDaddy?

### ISSUE THREAD

**Issue by nadesignlab** [niftylettuce/forward-email#35]
Hello! I've set up my DNS records to include the proper MX records, the SPF TXT record, and a DMARC TXT record. I cannot figure out how to set up a DKIM record for my domain on GoDaddy. Because of this (I think), I'm getting the following response when sending emails to email addresses at the domain:

     This is an automatically generated Delivery Status Notification.      

Delivery to the following recipients failed permanently:

  * XXXX@arpinofoundation.org

Reason: There was an error while attempting to deliver your message with [Subject: "Test Email 5"] to ksagami@arpinofoundation.org. MTA p3plmtsmtp03.prod.phx3.secureserver.net received this response from the destination host IP - 178.128.149.101 -  550 , 550 Please ensure the email service you are sending from either has SPF, DKIM, or is a top-ranked <30K Alexa.com domain. You can most likely resolve this problem by searching on Google for "$serviceName SPF DKIM setup" (be sure to replace $serviceName with your email service provider, e.g. "Zoho"). If you continue to have issues, please see https://forwardemail.net or file an issue on GitHub at https://github.com/niftylettuce/forward-email. We'd be glad to help out! -- @niftylettuce

If you need help with email-forwarding setup or troubleshooting please visit https://forwardemail.net
.

Reporting-MTA: dns; p3plmtsmtp03.prod.phx3.secureserver.net [184.168.131.199]
Received-From-MTA: dns; n83.mail01.mtsvc.net [216.70.64.234]
Arrival-Date: Tue, 04 Sep 2018 10:52:41 -0700

Final-recipient: rfc822; XXXX@arpinofoundation.org
Diagnostic-Code: smtp; 550 Please ensure the email service you are sending from either has SPF, DKIM, or is a top-ranked <30K Alexa.com domain. You can most likely resolve this problem by searching on Google for "$serviceName SPF DKIM setup" (be sure to replace $serviceName with your email service provider, e.g. "Zoho"). If you continue to have issues, please see https://forwardemail.net or file an issue on GitHub at https://github.com/niftylettuce/forward-email. We'd be glad to help out! -- @niftylettuce
Last-attempt-Date: Tue, 04 Sep 2018 10:53:12 -0700

========================================

What am I missing? I've tried searching 'GoDaddy SPF DKIM Setup' but to no avail. Any suggestions?

Thanks!

**Comment by rickyhewitt** [comment]
I have also experienced a similar issue -- missed an email due to the same error. The host had SPF/DKIM enabled.

> Smtp; 550 Please ensure the email service you are sending from either has SPF, DKIM, or is a top-ranked <30K Alexa.com domain. You can most likely resolve this problem by searching on Google for \"$serviceName SPF DKIM setup\" (be sure to replace $serviceName with your email service provider, e.g. \"Zoho\"). If you continue to have issues, please see https://forwardemail.net or file an issue on GitHub at https://github.com/niftylettuce/forward-email. We'd be glad to help out! -- @niftylettuce

**Comment by tylermenezes** [comment]
This is also an issue for me, sadly.

**Comment by nihakue** [comment]
Also struggling with this issue, I'm using netlify.com name servers / DNS, but Wordpress is the domain registrar. E-mails from well known providers like gmail get through fine, but some custom / less well known providers get a bounce with this message. Is there anything we can do to get around this? I'm afraid I'm missing e-mails. Thanks for the service, by the way. It's a tremendous achievement.

**Comment by nihakue** [comment]
Here's the message:

```
From:
"Mail Delivery System" <MAILER-DAEMON@smtpout.karoo.kcom.com>

To:
<the_recipient>@<the_recipient_domain>.com
Cc:

Sent:
17 Aug 2018 10:36:48 +0100
Subject:
Delivery Status Notification (Failure)
The following message to was undeliverable.
The reason for the problem:
5.3.0 - Other mail system problem 550-'Please ensure the email service you are sending from either has SPF, DKIM, or is a top-ranked <30K Alexa.com domain. You can most likely resolve this problem by searching on Google for "$serviceName SPF DKIM setup" (be sure to replace $serviceName with your email service provider, e.g. "Zoho"). If you continue to have issues, please see https://forwardemail.net or file an issue on GitHub at https://github.com/niftylettuce/forward-email. We\'d be glad to help out! -- @niftylettuce\n\n If you need help with email-forwarding setup or troubleshooting please visit https://forwardemail.net'

Reporting-MTA: dns; smtpout.karoo.kcom.com

Final-Recipient: rfc822;<me>@<my_domain>.com
Action: failed
Status: 5.0.0 (permanent failure)
Remote-MTA: dns; [178.128.149.101]
Diagnostic-Code: smtp; 5.3.0 - Other mail system problem 550-'Please ensure the email service you are sending from either has SPF, DKIM, or is a top-ranked <30K Alexa.com domain. You can most likely resolve this problem by searching on Google for "$serviceName SPF DKIM setup" (be sure to replace $serviceName with your email service provider, e.g. "Zoho"). If you continue to have issues, please see https://forwardemail.net or file an issue on GitHub at https://github.com/niftylettuce/forward-email. We\'d be glad to help out! -- @niftylettuce\n\n If you need help with email-forwarding setup or troubleshooting please visit https://forwardemail.net' (delivery attempts: 0)

@<my_domain>.com>
```
