### ISSUE TITLE
FAQ update request: how to check spam

### ISSUE THREAD

**Issue by bbuchalter** [niftylettuce/forward-email#40]
Thanks for your open source work!

I think an entry in the FAQ about "How to check for messages that aren't forwarded" would be a welcome addition. I expect for the hosted version this "feature" simply isn't practical, but for the self-hosted version, a few commands for how to do this would be most welcome. ❤️

**Comment by niftylettuce** [comment]
There is no support for this as we do not store logs.

There was a recent update and deployment this week that resolved all core outstanding issues with the service.  The deliverability rate should be extremely high and in only rare occasions should an issue occur.

If you want to host it yourself you could, and then turn on logs.
