### ISSUE TITLE
Improve documentation for mixed forwarding: one specific plus catch-all

### ISSUE THREAD

**Issue by rlogiacco** [niftylettuce/forward-email#47]
I'm using this fantastic service, but I've encounter a problem which I believe I've solved, but I had to try a couple of solutions before getting onto it: I wanted to forward all emails sent to a specific domain (*@mydomain.xyz) to an address (myanything@gmail.com) plus redirect a specific address of that same domain (info@mydomain.xyz) to another address (myinfo@gmail.com).

I've tried the following TXT record values:

- `forward-email=info:myinfo@gmail.com,myanything@gmail.com` seems not working producing an error **550 Invalid forward-email TXT record**
- `forward-email=myanything@gmail.com,info:myinfo@gmail.com` seems working

You might want to improve the documentation to cover this particular case.

I'm still testing this, so feel free to correct me if my solution is wrong.

**Comment by niftylettuce** [comment]
No longer needed per #46, this patch will be deployed soon to the server.

**Comment by shaneparsons** [comment]
@niftylettuce I didn't see an example of this in the docs... Is this the intended way to set this up?
`forward-email=catchall@example.com,info:info@example.com`

**Comment by rlogiacco** [comment]
> @niftylettuce I didn't see an example of this in the docs... Is this the intended way to set this up?
> `forward-email=catchall@example.com,info:info@example.com`

Yes, but now you can also specify those onto two separate TXT records, which might improve readability
