### ISSUE TITLE
Handle many forward-email entries

### ISSUE THREAD

**Issue by s1037989** [niftylettuce/forward-email#5]
TXT records are limited to 255 characters.

> Please note that if you have multiple TXT record lines for forward-email: the service will only read the FIRST listed - please ensure you only have one line.

From [RFC4408 3.1.3](https://tools.ietf.org/html/rfc4408#section-3.1.3):

> If a published record contains multiple strings, then the record MUST be treated as if those strings are concatenated together without adding spaces.

I don't see how the spf record and multiple forward-email TXT records would be able to be concatenated successfully.

Would love to see the README updated to show an example of many forwarding addresses to exceed 255 characters.

What would you think about supporting something like "forward-email-file:http://url.to/text/file.map"

Does the self-hosted option support getting the forward-email lookup map from somewhere other than TXT records?  It seems like it would be nice to keep that list private, yes?

**Comment by niftylettuce** [comment]
I'm open to that, just need some time to follow up here and implement, I have a lot else going on atm.

**Comment by niftylettuce** [comment]
@s1037989 @allanlaal @KennPunt I've just released support for this - please try it out.

**Comment by niftylettuce** [comment]
This is re-enabled again per my work with commit https://github.com/niftylettuce/forward-email/commit/3f84c922a008eac2cb3c8b094b9914d90044553d

Try it out and let me know if all works well!
