### ISSUE TITLE
forwardemail states protonmail has no SPF or DKIM but gmail lists them correctly

### ISSUE THREAD

**Issue by daboross** [niftylettuce/forward-email#53]
Hi,

I'm testing forwardemail for a domain I own (dabo.guru), just using https://forwardemail.net/ for now.

With the latest updates, when I sent an email from a protonmail account (@protonmail.com), it was returned as "Undelivered Mail Returned to Sender" with message:

> <dabo@dabo.guru>: host mx1.forwardemail.net[178.128.149.101] said: 550 Please ensure the email service you are sending from either has SPF or DKIM. You can most likely resolve this problem by searching on Google for "$serviceName SPF DKIM setup" (be sure to replace $serviceName with your email service provider, e.g. "Zoho"). (in reply to end of DATA command).

However, when I send directly to my gmail account that dabo.guru is set to forward to, gmail states that  the message passed both DKIM and SPF.

This is the report from gmail:

![gmail raw message screenshot](https://user-images.githubusercontent.com/1152146/47698475-bfa6ef80-dbcc-11e8-97bf-c0d0b7708960.png)

Hopefully this can help. If there's any more information that I can grab, I'll upload it.

I thought at first this was an error with protonmail, but it doesn't seem it allows for any user configuration of SPF or DKIM when sending from an @protonmail.com address, only when using a custom domain.

This isn't an urgent issue for me, but it'd be nice to figure out what's causing it. I've been using  protonmail to test for a while - it had some issues with DKIM before the last update that I'd hoped had been resolved but now I've run into this.

**Comment by niftylettuce** [comment]
@FGRibreau also posted a similar issue to me in Slack, I will investigate asap

**Comment by niftylettuce** [comment]
I have just fixed this issue @FGRibreau @nirfse @daboross and it has been deployed.  Please try again and it should work great 👍 	

Thanks for reporting! ❤️

**Comment by dyve** [comment]
I am running into the same issue, people e-mailing me from some accounts cannot send mail to my domain that is forwardmail-ed to gmail.

550 Please ensure the email service you are sending from either has SPF or DKIM. You can most likely resolve this problem by searching on Google for "$serviceName SPF DKIM setup" (be sure to replace $serviceName with your email service provider, e.g. "Zoho").

**Comment by felipecorrea9** [comment]
Same here, emailing from AWS Mail to my email I get same error. But if I send it from a Gmail account it works fine,

**Comment by niftylettuce** [comment]
If you can provide full original email with headers I can help you debug further.

Feel free to send it to niftylettuce@gmail.com if you'd like to keep it private.

The most common problem is that the sender of the email does not have SPF nor DKIM setup as the error code indicates, however there might be an underlying issue not obvious I can help with - but only if I have a full original copy of the email with headers.

Another thing you can do is just send an email to niftylettuce@gmail.com from the email address that's not working as a sender.

**Comment by felipecorrea9** [comment]
THanks  I just sent you an email with the mail header that I got from printing "rawEmail" variable at line https://github.com/niftylettuce/forward-email/blob/master/index.js#L302

**Comment by felipecorrea9** [comment]
The wird thing is that the same thing does work with "forwardemail.net" but not with my self hosted.

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.
