### ISSUE TITLE
Message not delivered - please log in via your web browser

### ISSUE THREAD

**Issue by emmerich** [niftylettuce/forward-email#57]
Hi nifty,

I've followed the steps for "Send mail as" but unfortunately I'm not able to send mails due to the error "You're sending this from another Google account using the 'Send mail as' feature."

Any ideas how I can fix this problem?

Email dump:
`534 5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=...> Please log in via your web browser and then try again. Learn more at https://support.google.com/mail/answer/78754 z12-v6sm3000767edk.43 - gsmtp`

Email was my first name [at] olderhall.com

**Comment by niftylettuce** [comment]
Can you please try again and let me know?  I just fixed a core issue with DMARC and it might be related.

**Comment by emmerich** [comment]
All good.
