### ISSUE TITLE
Why leave Gmail "Treat as an alias" unchecked

### ISSUE THREAD

**Issue by dyve** [niftylettuce/forward-email#61]
If you leave the Gmail checkbox for "Treat as an alias" unchecked (as per docs), Gmail doe snot treat your external address as `from:me` in searches.

Is there a specific reason why you should not set your own domain name as an alias in Gmail?

**Comment by niftylettuce** [comment]
No reason in particular, I guess I can remove that option.  Thanks for heads up.

**Comment by dyve** [comment]
👍 Thanks for this great app and service!
