### ISSUE TITLE
Message not delivered - please log in via your web browser 

### ISSUE THREAD

**Issue by Resumane** [niftylettuce/forward-email#62]
Hi, I believe I did every step in your tutorial correctly but each time I tried to send a message (send as in gmail) I'm getting:

> You're sending this from another Google account using the 'Send mail as' feature. To send this message, please log in: 
> Message not delivered - please log in via your web browser 

After I click and log in (but I'm already logged in of course, which is weird) I can send the message.

**Comment by whatisthisidont** [comment]
I have the same issue, but logging in doesn't solve it.

**Comment by niftylettuce** [comment]
If you can email me niftylettuce@gmail.com with your domain names being used I can help further investigate.

**Comment by nscorpionking** [comment]
sent a test mail from my email id and got the bellow error

The response from the remote server was:
550 Invalid forward-email TXT record.

**Comment by niftylettuce** [comment]
@nscorpionking 	what is your domain name? feel free to email me.  your TXT records are incorrect.

**Comment by nscorpionking** [comment]
mail@naveenn.ml
