### ISSUE TITLE
Not working with Cargo Collective DNS

### ISSUE THREAD

**Issue by whatisthisidont** [niftylettuce/forward-email#63]
Hi.

I had incoming mail forwarding working perfectly with GoDaddy NS Servers, then recently had to move to Cargo Collective NS Servers (for some reason they require this for domain forwarding.) I made sure to move all of the relevant DNS records.

Now when I send emails out to my domain (amirsteinberg.com), forwarding doesn't work anymore.
Any clue?

Thanks for the amazing service!

**Comment by niftylettuce** [comment]
I think you just had to wait for DNS to propagate?  I'll send you a test email now.

**Comment by niftylettuce** [comment]
@whatisthisidont if you try to send to yourself it should work OK now btw 👍
