### ISSUE TITLE
Sending mail timeout 

### ISSUE THREAD

**Issue by soyuka** [niftylettuce/forward-email#68]
Hi!

I've setup my own forward-email service, I think that I have everything setup correctly but sending mails keep timing out. 

Log extract (sending a mail from `soyuka@gmail.com` to `antoine@bluchet.fr` that should forward to `soyuka@protonmail.com`:

```
4520 : (out) [2018-12-11 16:24:19] INFO  [#n2pi66csatz2vo4d] Connection from mail-ed1-f48.google.com
...
4520 : (out) [2018-12-11 16:24:19] DEBUG [#n2pi66csatz2vo4d] C: MAIL FROM:<soyuka@gmail.com> SIZE=2568
4520 : (out) [2018-12-11 16:24:19] DEBUG [#n2pi66csatz2vo4d] S: 250 Accepted
4520 : (out) [2018-12-11 16:24:19] DEBUG [#n2pi66csatz2vo4d] C: RCPT TO:<antoine@bluchet.fr>
4520 : (out) [2018-12-11 16:24:19] DEBUG [#n2pi66csatz2vo4d] S: 250 Accepted
4520 : (out) [2018-12-11 16:24:19] DEBUG [#n2pi66csatz2vo4d] C: DATA
4520 : (out) [2018-12-11 16:24:19] DEBUG [#n2pi66csatz2vo4d] S: 354 End data with <CR><LF>.<CR><LF>
4520 : (out) [2018-12-11 16:24:20] DEBUG Creating transport: nodemailer (4.6.8; +https://nodemailer.com/; SMTP/4.6.8[client:4.6.8])
4520 : (out) [2018-12-11 16:24:20] DEBUG Sending mail using SMTP/4.6.8[client:4.6.8]
...  Takes time here
4520 : (out) [2018-12-11 16:25:20] DEBUG [#n2pi66csatz2vo4d] S: 421 Timeout - closing connection
... a bit later
4520 : (out) [2018-12-11 16:26:20] ERROR Send Error: Connection timeout
4520 : (err) { Error: Connection timeout
4520 : (err)     at SMTPConnection._formatError (/home/soyuka/forward-email/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
4520 : (err)     at SMTPConnection._onError (/home/soyuka/forward-email/node_modules/nodemailer/lib/smtp-connection/index.js:579:20)
4520 : (err)     at Timeout._connectionTimeout.setTimeout (/home/soyuka/forward-email/node_modules/nodemailer/lib/smtp-connection/index.js:261:18)
4520 : (err)     at ontimeout (timers.js:436:11)
4520 : (err)     at tryOnTimeout (timers.js:300:5)
4520 : (err)     at listOnTimeout (timers.js:263:5)
4520 : (err)     at Timer.processTimers (timers.js:223:10) code: 'ETIMEDOUT', command: 'CONN' }
```

/edit: it looks like the mail tries to be sent to gmail instead of protonmail anyway (changed the TXT record not long ago) maybe it's because of the provider?

[Full log](https://gist.github.com/soyuka/9465dc76b9288e9624126ff19a268d18)

TXT forward instruction: `forward-email=antoine:soyuka@protonmail.com`.

[MX Lookup](https://mxtoolbox.com/SuperTool.aspx?action=mx%3abluchet.fr&run=toolpage) looks good, DMark is also green as does [spf](https://mxtoolbox.com/SuperTool.aspx?action=spf%3abluchet.fr&run=toolpage#).
The [smtp server test](https://mxtoolbox.com/SuperTool.aspx?action=smtp%3abluchet.fr&run=toolpage) reports all green too.

What am I missing? Note that I've carefully noted every step I used to set up my own instance of forward-email and am going to add some documentation about this if you want me to!

Thanks for your help!

/edit: Apparently Scaleway blocks smtp by default, just discovered that you had to disable the smtp block manually by going to the Security panel.

**Comment by soyuka** [comment]
Ok for future reader using scaleway, you have to disable their smtp security. This software works as expected!

**Comment by niftylettuce** [comment]
To anyone that still encountered this issue, there was one more bug due to host normalization that needed fixed.  It's all resolved now though, was pesky to track down! 🎉 

Any further issues, questions, or feature requests, please let us know.

v6.1.4 has been released and deployed, which fixed this issue through some added "host normalization" logic.
