### ISSUE TITLE
forwarding not working for Yahoo domain

### ISSUE THREAD

**Issue by dani681** [niftylettuce/forward-email#70]
I have my domain masterrealtyinc.com managed by Yahoo Small Business. I used to have a website hosted by a 3rd party, which I have cancelled. I reset all the DNS records back to Yahoo's default. I then edited the MX records to the two forwardemail hosts, and added the two TXT records to accomplish forwarding of all masterrealtyinc emails to my gmail address (brokeravi@gmail.com). However, I am unable to get this forwarding to work. When I sent a test e-mail from another gmail address, I get no returned failures or any other indication that the forwarding wasn't successful - I just never receive the email at brokeravi. I tried to send another test email from an Outlook exchange account, and this time I got the following back as a failure:
************************************************
This is a delivery failure notification message indicating that an email you addressed to email address :
-- avi@masterrealtyinc.com

could not be delivered. The problem appears to be :
-- Recipient email address is possibly incorrect

Additional information follows :
-- queryTxt ESERVFAIL masterrealtyinc.com

This condition occurred after 1 attempt(s) to deliver over a period of 0 hour(s).

If you sent the email to multiple recipients, you will receive one of these messages for each one which failed delivery,  otherwise they have been sent.
************************************************
I really don't know what I'm doing wrong here. Any help would be appreciated.

**Comment by niftylettuce** [comment]
I sent you a test email, I think the DNS just hadn't propagated yet.  You're using Yahoo which is probably as bad as GoDaddy.

**Comment by niftylettuce** [comment]
This is re-enabled again per my work with commit https://github.com/niftylettuce/forward-email/commit/3f84c922a008eac2cb3c8b094b9914d90044553d

Try it out and let me know if all works well!
