### ISSUE TITLE
SPF Confirmation

### ISSUE THREAD

**Issue by jotcreative** [niftylettuce/forward-email#72]
The instructions say `3. Set (and customize) the following TXT record for SPF verification for your domain name (this will allow SPF verification to pass):`

But I'm assuming that we're NOT supposed to _customize_ the URL (spf.forwardemail.net) portion of the value, correct?

I'm still getting SPF failures, and I'm wondering if I just have to wait for propagation. When I added the MX servers to Cloudflare, they propagated almost instantly, so I assumed that SPF would be similarly quick.

Thanks!

**Comment by hungrycactus** [comment]
What were the instructions?  I think my issue #75 is related.

**Comment by niftylettuce** [comment]
Whatever email you're sending tests with doesn't have SPF or DKIM setup, that's the issue, I think I replied to you by email already

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.
