### ISSUE TITLE
Sending FROM Gmail Forwarding Address to Custom Domain Forwarding Address

### ISSUE THREAD

**Issue by jeffreywescott** [niftylettuce/forward-email#73]
Hi. Thanks for this awesome service!

I saw in #10 that someone noted that any emails they sent from their own gmail account forwarding address to their configured domain were marked as spam. My problem is _slightly_ different ...

I can receive _external_ emails just fine. In other words, if some 3rd party sends an email to my domain, it gets forwarded to my gmail just fine.

But if I try to send a mail _from_ my gmail forwarding address _to_ my domain, it doesn't get marked as spam, it just ... is never received.

Have you seen this?

**Comment by niftylettuce** [comment]
Haven't seen this issue - do you still encounter it?

**Comment by jeffreywescott** [comment]
Yes -- still experiencing it.

**Comment by jeffreywescott** [comment]
If it helps, my domain is `wip.today`.

**Comment by niftylettuce** [comment]
@jeffreywescott I reproduced this by the way, not sure how to fix yet, will have to test more when I get a chance hopefully this weekend

**Comment by jeffreywescott** [comment]
Ah -- glad to hear it's not something on my end. Thanks for keeping me posted. :)

**Comment by mariux** [comment]
you cannot send to the same gmail account you are using as from address. e.g. 

`me@gmail.com -> me@mydomain.tld -> me@gmail.com`
will fail with mail being accepted by gmail but not show up in inbox.

It's a known gmail thing.

to test forwarding use another account:
`other@gmail.com -> my@mydomain.tld -> me@gmail.com`

also you should think about implementing SRS (if not already done?) so that those email don't go to spam that often. hope it helped - if not.. ignore ;)

**Comment by niftylettuce** [comment]
SRS is not yet implemented cc @mariux 

https://www.libsrs2.org/srs/srs.pdf

**Comment by niftylettuce** [comment]
@mariux I will implement a workaround now to alleviate the Gmail test issue.  If you are testing from yourself it will do a friendly-from rewrite so that the message will show in your inbox.

**Comment by niftylettuce** [comment]
I have deployed the fix, you should be able to send email FROM your Gmail TO a Forward Email address that resolves to the FROM.  Let me know of any further issues.

**Comment by niftylettuce** [comment]
@jeffreywescott 	can you confirm this is fixed? cc @mariux

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.

**Comment by JCAguilera** [comment]
I'm having this exact issue.
