### ISSUE TITLE
receiving person sees "via forwardemail.net" / SPF softfail (in gmail)

### ISSUE THREAD

**Issue by hungrycactus** [niftylettuce/forward-email#75]
Hi -- I noticed whenever I send an email through forwardemail.net using the "send as gmail", the emails show "via forwardemail.net" in the from field.  Is there any way to get rid of that?

Update:It seems to be a security feature in gmail? https://support.google.com/mail/answer/1311182?hl=en

> Gmail checks whether the messages you send are authenticated.
> 
> If you send messages using a bulk mailing vendor or a third party affiliates, check out Gmail's Bulk Senders Guidelines, including: Publish an SPF record that includes the IPs of the vendor or affiliates which send your messages.
> Sign your messages with a DKIM signature that is associated with your domain.
> Make sure the domain in the "From:" address matches the domain you're using to authenticate your emails.

~ ~ ~ 

I have this set in my DNS configuration (TXT record): v=spf1 a mx include:spf.forwardemail.net -all

Emails I receive show the SPF is not passing:

> ARC-Authentication-Results: i=1; mx.google.com;
>        dkim=pass header.i=@forwardemail.net header.s=default header.b=T0ZKcmZ2;
>        spf=softfail (google.com: domain of transitioning XXXXX@gmail.com does not designate 178.128.149.101 as permitted sender) 

> Received-SPF: softfail (google.com: domain of transitioning XXXXX@gmail.com does not designate 178.128.149.101 as permitted sender) client-ip=178.128.149.101;
> Authentication-Results: mx.google.com;
>        dkim=pass header.i=@forwardemail.net header.s=default header.b=T0ZKcmZ2;
>        spf=softfail (google.com: domain of transitioning XXXXX@gmail.com does not designate 178.128.149.101 as permitted sender)

**Comment by niftylettuce** [comment]
Yes this is in Gmail and no way around it, this is actually a good thing.

**Comment by niftylettuce** [comment]
SPF issues are all resolved

Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.

**Comment by niftylettuce** [comment]
ARC has been deployed.  No more friendly-from rewrites.  No more "no-reply@forwardemail.net".  I've also removed SRS, so that Gmail and vacation responders do not have edge case formatting issues.
