### ISSUE TITLE
Need CJK support (encoding issue)

### ISSUE THREAD

**Issue by auzeonfung** [niftylettuce/forward-email#79]
Hi there!

I configured the mail forwarding service according to the instructions on  https://forwardemail.net/

And I found a encoding issue which will let all the non-alphabet contents goes wrong.

Like this:

$BGg@'0lIuB,;nMQE*M97o(B
This is a test email.

iPhone$B$+$iAw?.(B

Which the original is:

這是一封測試用的郵件
This is a test email.

iPhoneから送信

Thank you!

**Comment by niftylettuce** [comment]
I just tested this and it seems to work OK on our end.  I also wrote a test case and it passed just fine.

Screenshots:

![screen shot 2019-01-10 at 2 57 28 am](https://user-images.githubusercontent.com/523141/50957325-94ba0100-1483-11e9-8b38-39dc5c8ae721.png)
![screen shot 2019-01-10 at 2 53 30 am](https://user-images.githubusercontent.com/523141/50957326-94ba0100-1483-11e9-82cb-c1c804d89265.png)

**Comment by niftylettuce** [comment]
Can you please provide me with more information such as how you are sending the email with non-alphabet characters?  Are you using a webmail service such as Outlook?

**Comment by auzeonfung** [comment]
Thanks for your reply. ：）

I use mail.app on iOS to sent this email through my Yahoo Japan's email account.

There are also problems with emails sent to me by third parties.

<img width="663" alt="2019-01-11 00 07 08" src="https://user-images.githubusercontent.com/3320227/50977144-f9816400-1534-11e9-8522-90be3e3c541a.png">

Before I set up this forwarding service, the email sent to me by the same sender can be displayed normally.

And here is a similar email sent to me by the same sender can be displayed normally before I setting up this forwarding service.
<img width="549" alt="2019-01-11 00 13 05" src="https://user-images.githubusercontent.com/3320227/50977533-d905d980-1535-11e9-8a99-d86726456e91.png">

if you need more information please let me know 😄
Thank you!

**Comment by auzeonfung** [comment]
I also got some undelivered error emails from my sender account's server when I tried to send some test email with non-alphabet characters.
Maybe it's marked as spam by Gmail because encode issue...?

[https://gist.github.com/auzeonfung/73b4cac64385e28f579036b786f7aa7e](url)

**Comment by niftylettuce** [comment]
should be resolved now with the version 2 release!
