### ISSUE TITLE
How to set catch-all email when forwarding multiple emails?

### ISSUE THREAD

**Issue by KennPunt** [niftylettuce/forward-email#8]
**forwarding multiple emails**
forward-email=hello:niftylettuce@gmail.com,support:niftylettuce@gmail.com

**If I would add this ->**
forward-email=hello:niftylettuce@gmail.com,support:niftylettuce@gmail.com, niftylettuce@gmail.com
**would the last entry be a catch-all?**

**Comment by niftylettuce** [comment]
@KennPunt sorry for the delay, have been very busy

To answer your question - no, not yet.  We'd need to modify this bit of the codebase to properly parse all forwarded emails until we found the best result.  Right now it just looks for a catch all as the first entry.  <https://github.com/niftylettuce/forward-email/blob/master/index.js#L547

**Comment by allanlaal** [comment]
I'd love this too :)

**Comment by niftylettuce** [comment]
This is re-enabled again per my work with commit https://github.com/niftylettuce/forward-email/commit/3f84c922a008eac2cb3c8b094b9914d90044553d

Try it out and let me know if all works well!
