### ISSUE TITLE
SPF DKIM from exchange server (Outlook)

### ISSUE THREAD

**Issue by tombert-zz** [niftylettuce/forward-email#80]
Hi,

When sending emails from Outlook (Exchange server) I get the reply:

> iagnostic-Code: smtp; 550 Please ensure the email service you are sending from either has SPF or DKIM. You can most likely resolve this problem by searching on Google for "$serviceName SPF DKIM setup" (be sure to replace $serviceName with your email service provider, e.g. "Zoho").
> Remote-MTA: 178.128.149.101
> 

I am testing from my company (ATOS). I doubt that they did not setup SPF right.
When sending emails from gmail or hotmail all works fine.

Any idea what could be wrong?

Regards

**Comment by niftylettuce** [comment]
Can you send me the domain name of ATOS?  I can help you to confirm whether or not they have SPF and DKIM setup properly.

**Comment by tombert-zz** [comment]
my ATOS email ends with @atos.net

thx for your support!

**Comment by niftylettuce** [comment]
@tombert-zz it looks like SPF is setup on your domain, however I'm not sure what the IP address is that you're sending from, which is what matters.  can you send me the full original message including headers of a test email privately? niftylettuce@gmail.com

Are you using Exchange Online? Sending something from on-premise?  It appears SPF is setup properly, but again I'm not sure what the IP is that you're sending from but I'd be able to help more if you sent full headers/original message to me.

SPF report: https://mxtoolbox.com/SuperTool.aspx?action=spf%3aatos.net&run=toolpage

**Comment by niftylettuce** [comment]
@tombert-zz you could send a test from your atos to niftylettuce@gmail.com as well btw

**Comment by tombert-zz** [comment]
Send you a test-mail privately from my ATOS address.

**Comment by tombert-zz** [comment]
Forwared the mail headers

**Comment by tombert-zz** [comment]
I also tried sending from Office365 online. Same result - does not work.

**Comment by niftylettuce** [comment]
Got them, reviewing now

**Comment by niftylettuce** [comment]
Here is the issue @tombert-zz.

Your "FROM" address is not formatted properly, and our address parser is unfortunately parsing it incorrectly.  However this shouldn't need to be fixed on your end, it should be fixed on ours as well.

There's some code in our project...

```js
const addressParser = require('nodemailer/lib/addressparser');

console.log(addressParser('*******, ******* <*******.*******@atos.net>')[0].address);
```

Outputs:

```sh
undefined
```

Whereas:

```js
console.log(addressParser('"*******, *******" <*******.*******@atos.net>')[0].address);
```

Outputs:

```sh
*******@atos.net
```

Encapsulating your first and last name, which is comma separated, fixes the issue.

What happens if we have logic that gets passed to a function `validateSPF` which is returning `false` (and indicating that SPF fails) - this is because the value passed to it for your FROM email is `undefined` vs. `*******.*******@atos.net`

I will write a fix in the meanwhile...

**Comment by niftylettuce** [comment]
I have just deployed the fix, please let me know if this resolves the issue for you.

**Comment by tombert-zz** [comment]
Yes, works now.
Really thank you very much for this service!

**Comment by contactalexliu** [comment]
Same here, working now with UCLA and wbcgp.com emails too from #77.
Can't express enough thanks for your time and continuous effort on this project!

**Comment by niftylettuce** [comment]
thanks for letting me know, appreciated @contactalexliu

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.
