### ISSUE TITLE
Set multiple forward to the same address

### ISSUE THREAD

**Issue by Gil-1** [niftylettuce/forward-email#82]
I'm not sure if it's a bug but if I have multiple forward email to the same recipient they don't seem to work.

## Example

```
forward-email=postmaster:example@gmail.com,forward:example@gmail.com
```
I tried to put them all in one line & multiple (as of now) but then I receive an error.
Using multiple lines allows to make some of the aliases to work.

## Error line

```
Remote server returned an error -> 550 Invalid forward-email TXT record
```

**Comment by dprogramming** [comment]
I seem to have similar issues. Any idea what could be causing this? I'm pretty sure the TXT records are correct.

**Comment by niftylettuce** [comment]
if you can share your domain names I can help further debug

**Comment by niftylettuce** [comment]
feel free to email me privately at niftylettuce@gmail.com

**Comment by niftylettuce** [comment]
oh, sorry, this feature is not yet implemented.  someone submitted a pull request though that adds support for it. I will keep you all posted!! 😄

**Comment by dprogramming** [comment]
Thank you very much!

**Comment by Gil-1** [comment]
I tested aftter ready your comment @dprogramming but it doesn't work for me.
@niftylettuce you can check cynaptek.com if you like. I'm the only one to receive mails from info@cynaptek.com

**Comment by Gil-1** [comment]
@dprogramming Quick update on this. I tried the solution to leave 2 TXT records but it appears we are receiving sometimes on one email and sometimes on the other.
We need to wait till the PR is merged.

**Comment by niftylettuce** [comment]
This is re-enabled again per my work with commit https://github.com/niftylettuce/forward-email/commit/3f84c922a008eac2cb3c8b094b9914d90044553d

Try it out and let me know if all works well!
