### ISSUE TITLE
Forwarding mail to posteo.de fails: 504 Invalid HELO

### ISSUE THREAD

**Issue by heikojansen** [niftylettuce/forward-email#83]
I have set up my DNS so that three different addresses should be forwarded to three distinct target addresses; one of which is at "web.de" and the other two are at "posteo.de".
If I send a mail from a GMail account to the one that should forward to the web.de target it is delivered there just fine.
Sending mails to the other addresses however does not work. They are not forwarded and the GMail address receives a delivery failure message which states:

`504 Invalid HELO. response=504 5.5.2 <mx1>: Helo command rejected: need fully-qualified hostname`

Since it works for one address I believe I have set up the DNS config correctly and I have otherwise no idea what's wrong...

**Comment by niftylettuce** [comment]
You need to send from a FQDN, not using an IP

**Comment by heikojansen** [comment]
Thanks for looking into this.
Unfortunately I still don't understand what I'm doing wrong.
My domains DNS is set up like this:

```
@      IN A       195.201.xxx.xxx
@ 3600 IN MX 10   mx1.forwardemail.net.
@ 3600 IN MX 20   mx2.forwardemail.net.
@ 3600 IN TXT     "forward-email=chico:john@posteo.de,harpo:paul@web.de,groucho:george@posteo.de"
@ 3600 IN TXT     "v=spf1 a mx include:spf.forwardemail.net -all"
```
Now if I send a test mail via the web interface of my Google Mail account to `harpo@domain.com` it is delivered to `paul@web.de` just fine. 
But if I send a mail to `chico@domain.com` I see a response in my Google Mail account with the error shown above.

I don't see where I am supposed to replace an IP by a FQDN?

**Comment by fedus** [comment]
Actually I have exactly the same issue (also using Posteo). Any ideas?

**Comment by niftylettuce** [comment]
Should be resolved now!!!

```sh
deploy@mx1:~$ node -i
> require('os').hostname()
'mx1.forwardemail.net'
```
