### ISSUE TITLE
Is forwarding down?

### ISSUE THREAD

**Issue by coderam** [niftylettuce/forward-email#9]
I setup my MX and TXT DNS entries but no goodness when attempting to email?  Any ideas?

Just emailed you :)

Love only,

**Comment by niftylettuce** [comment]
No it is online, if you still have issues let me know

**Comment by niftylettuce** [comment]
If you try again it should be fine.  Let me know otherwise!  If you want to forward me any rejections/issues/bounced mail you can at niftylettuce@gmail.com for me to further investigate.  I fixed quite a few issues recently.

**Comment by niftylettuce** [comment]
@coderam can you please try the service again? I recently implemented a vast number of improvements and DKIM/SPF/DMARC validation should be perfect now (this means deliverability should be perfect).
