### ISSUE TITLE
How to send a mail with Nodemailer

### ISSUE THREAD

**Issue by MCPE-PC** [niftylettuce/forward-email#90]
Using Nodemailer: the mail is not delivered, even though it says it is sent. But when I send mail with Gmail, it is delivered.
How can I send as forwardemail using Nodemailer?

**Comment by niftylettuce** [comment]
This issue you posted isn't very descriptive.  What is the full error message you receive?  What does your code look like for sending an email to an email address using forwardemail.net's servers?
