### ISSUE TITLE
Postfix vs Forwardemail

### ISSUE THREAD

**Issue by tomcontr** [niftylettuce/forward-email#91]
What is the mail difference between using virtual alias in postfix and forwardemail?

Regards!

**Comment by niftylettuce** [comment]
Postfix is unnecessary bloat.  This project requires zero-setup and we have a hosted, free version online for you to use.  The code itself that runs on our secure servers is less than 1000 LOC.

**Comment by niftylettuce** [comment]
Also Postfix out of the box does not have features we do such as the use of DNSBL and more spam prevention measures.  See our README for more insight here <https://github.com/niftylettuce/forward-email#how-do-you-prevent-spammers-and-ensure-good-email-forwarding-reputation>.
