### ISSUE TITLE
550 Disposable email addresses are not permitted

### ISSUE THREAD

**Issue by dmytrohoi** [niftylettuce/forward-email#93]
Google was response `550 Disposable email addresses are not permitted` to my sending letter on `dmytro@hoi.pp.ua`.

I was create Issue to disposable-email-domains about my hostname, and now hostname not in list of disposable. > https://github.com/ivolo/disposable-email-domains/issues/460

**Comment by niftylettuce** [comment]
@dmytrohoi I have fixed this and deployed the latest update to our servers.   You should be able to receive email just now now with your `pp.ua` email address.  Let me know otherwise.

**Comment by niftylettuce** [comment]
We are allowing all disposable emails with the v7.0.0 release soon. I will comment again here once this is LIVE.

**Comment by niftylettuce** [comment]
Deployed!
