### ISSUE TITLE
TypeError: forwardEmail.listen is not a function

### ISSUE THREAD

**Issue by gomorizsolt** [niftylettuce/forward-email#95]
I'm trying to setup a self-hosted service on a DigitalOcean server in order to try the basic functionalities out. Followed the given steps in the documentation, but whenever I run `forwardEmail.listen()` the console responses with an error that *listen* is not a function.

How could it happen? Another question is whether the doc is up-to-date or not.

This likely happens because I miss / misunderstand something, as there is no issue that is related to this one. Whether it's a silly question or not, I couldn't find anything that might solve the problem.

If this information isn't enough, let me know. 

I'd appreciate any kind of help.

**Comment by niftylettuce** [comment]
It's `forwardEmail.server.listen`.

I updated the README as well for the API documentation to reflect this.

Also, version 2 is released with major updates.
