### ISSUE TITLE
Neutral SPF but still being enforced

### ISSUE THREAD

**Issue by aletorrado** [niftylettuce/forward-email#97]
Hi, I've noticed that ForwardEmail is enforcing SPF on a domain with a neutral SFP (`?all`).

Any e-mail sended that matches with this directive should be delivered, because it's equivalent to not having an SFP rule for the domain, but ForwardEmail is rejecting those e-mails anyway.

**Comment by niftylettuce** [comment]
If you do not have SPF set up or you are doing a neutral SPF on your domain that is a very, very bad practice.

**Comment by aletorrado** [comment]
It is, indeed. However SPF is an opt-in feature.

**Comment by niftylettuce** [comment]
I do not wish to allow my service to be used by people that do not take security seriously.

**Comment by aletorrado** [comment]
I understand that this is your choice for the free service you provide.

I just want to make it clear that it's not up to me or any other user of your service to get SPF implemented in every single person who sends an e-mail to a forward-email handled domain.

Not receiving e-mails from legacy remitents doesn't seem acceptable for me, and this should be a deal-breaker even for yourself.

**Comment by niftylettuce** [comment]
@aletorrado It's not a deal breaker for myself.  We are enforcing best practices.  This is a standard.  It's 2019.  We send an error message to the sender indicating that they need to setup SPF (or) DKIM properly on their email.

**Comment by nahoskins** [comment]
This makes it impossible to rely on this service. There should be an obvious work around for people who rely on their email for work.

**Comment by niftylettuce** [comment]
I will allow this.  One moment.

**Comment by niftylettuce** [comment]
If the result is `none`, `pass`, or `neutral`, then it will be OK.  Adding this in now... need a moment

**Comment by niftylettuce** [comment]
This is now resolved.  Emails will send through our system properly if they have SPF of none, neutral, or pass result or if the email itself does not even have a DKIM signature.  This is much more lax while still enforcing both email standards.  Hope this helps.  The fixes are deployed and you can test immediately.  Let me know of any issues. thank you.

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.
