### ISSUE TITLE
DKIM or SPF enforcement should be optional.

### ISSUE THREAD

**Issue by nahoskins** [niftylettuce/forward-email#99]
Some people rely on emails from clients for their livelihood. Of that set of emails, a subset fail to be delivered due to misconfigured DKIM/SPF. This failure is silent and costs users leads/revenue.

For self-hosted deployments, there should exist a simple guide to removing SPF/DKIM requirements.

The policy of "everyone should be using best practices" is naive.

Currently, this service provides **NO** warning that an email has failed to make it to your inbox. The burden is thus on the client to figure out how to contact you about the error they perceive as _YOUR FAULT_.

Everyone should be able to use this service. It is a **fantastic application.**

But MANY of us need our email to reach us from technically deficient clients.

I've only skimmed the file but I can't imagine just commenting out the if statement on line 308 will be sufficient.

Some of us don't have the luxury of following the moral high ground on this issue. _We need our clients to reach us, no matter how stupid their set up is._

**Comment by niftylettuce** [comment]
Feel free to send a PR along with tests

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.
